title: Master Konsult
url: "https://www.masterkonsult.com/"
baseurl: 
locale: it_IT

# Default description in social shares for the jekyll-seo-tag gem
hero-msg: Diventa impresa digitale
description: "Un team innovativo dedicato alle imprese ed alla pubblica amministrazione, esperti di nuove tecnologie, sicurezza informatica, e di semplificazione aziendale, che collaborano fianco a finaco per offrire una risposta completa a tutte le esigenze dell'impresa digitale."

timezone: Europe/Rome

collections:
  staff_members:
    output: false
  servizi:
    output: false
    sort_by: order
  customers:
    output: false
  chi_siamo:
    output: false

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
  - "docker-compose.yml"

include:
  - _redirects

defaults:
  - scope:
      path: ""
      type: "servizi"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
