[build]
    command = "bundle exec jekyll build"
[context.production]
    command = "JEKYLL_ENV=production bundle exec jekyll build"
[context.develop]
    command = "JEKYLL_ENV=test bundle exec jekyll build"
    [context.develop.environment]
        GA_ID = "G-2SKTNSFLC8"
        GTAG_ID = "GTM-WPZRS4V"
[[redirects]]
    from = "/*"
    to = "/404"